export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    overview: '/dashboard',
    account: '/dashboard/account',
    customers: '/dashboard/customers',
    users: '/dashboard/users',
    species: '/dashboard/species',
    organisms: '/dashboard/organisms',
    traits: '/dashboard/traits',
    properties: '/dashboard/properties',
    traitProperties: (traitId: number | string) => `/dashboard/properties/${traitId}`,
    traitPropertiesCreate: (traitId: number | string) => `/dashboard/properties/${traitId}/create`,
    traitPropertiesUpdate: (propertyId: number | string) => `/dashboard/properties/update/${propertyId}`,
    traitUpdate: (traitId: number | string) => `/dashboard/traits/update/${traitId}`,
    traitCreate: '/dashboard/traits/create',
    integrations: '/dashboard/integrations',
    settings: '/dashboard/settings',
    batchProcesses: '/dashboard/batch',
    organismsBatchCreate: '/dashboard/organisms/batch/create',
    organismsBatchDelete: '/dashboard/organisms/batch/delete',
    locations: '/dashboard/location',
    locationUpdate: (locationId: number | string) => `/dashboard/location/update/${locationId}`,
    locationCreate: '/dashboard/location/create/',
    locationPropertiesAdd: (locationId: number | string) =>  `/dashboard/location/properties/add/${locationId}`,
    locationPropertyUpdate: (locationPropertyId: number | string) =>  `/dashboard/location/properties/update/${locationPropertyId}`,
    samplingAreas: '/dashboard/samplingarea',
    samplingAreaUpdate: (samplingAreaId: number | string) => `/dashboard/samplingarea/update/${samplingAreaId}`,
    samplingAreaCreate: '/dashboard/samplingarea/create/',
    projects: '/dashboard/projects',
    projectUpdate: (projectId: number | string) => `/dashboard/projects/update/${projectId}`,
    projectCreate: '/dashboard/projects/create',
    persons: '/dashboard/persons',
    personUpdate: (personId: number | string) => `/dashboard/persons/update/${personId}`,
    personCreate: '/dashboard/persons/create',
    userUpdate: (userId: number | string) => `/dashboard/users/update/${userId}`,
    externalDatasets: '/dashboard/externaldatasets',
    externalDatasetUpdate: (externalDatasetId: number | string) => `/dashboard/externaldatasets/update/${externalDatasetId}`,
    externalDatasetCreate: '/dashboard/externaldatasets/create',
    typeDatasets: '/dashboard/typedatasets',
    typeDatasetUpdate: (typeDatasetId: number | string) => `/dashboard/typedatasets/update/${typeDatasetId}`,
    typeDatasetCreate: '/dashboard/typedatasets/create',
  },
  errors: { notFound: '/errors/not-found' },
} as const;
